### PR TITLE
Improve how scanners are displayed

### PR DESCRIPTION
**Pull request by gpotter2**
part of https://github.com/ivre/ivre/pull/1175

This PR:
- a few improvements to how scanners are displayed (now also displays which probe were found to be able to identify false positives, if any)

### CODE REVIEW

**Review by p-l- — DISMISSED** [review]

**Comment by p-l-** [comment]
Hi, it seems that [black](https://github.com/psf/black) is not happy with your PR. Can you have a look?

**Comment by p-l-** [comment]
Still KO (black again)

**Comment by gpotter2** [comment]
Sorry about that I was using ubuntu's black which is outdated.

**Comment by p-l-** [comment]
Now it seems you have a typing problem

**Review by p-l- — APPROVED** [review]

**Review by p-l- — CHANGES_REQUESTED** [review]
Sorry I missed that but this will only affect merged hosts, so you may want to apply a similar change to [ivre/view#L253](https://github.com/ivre/ivre/blob/master/ivre/view.py#L153) so that host that do not require a merge for the pseudo script `scanner` get the new output.

**Comment by gpotter2** [comment]
Makes sense. I only tested this on passive where merging always happen (https://github.com/ivre/ivre/blob/96963faf1c0e82bdcfa94e02af7963d68de8ca16/ivre/view.py#L722)

**Review by p-l- — APPROVED** [review]

**Pull request merged**
